### PR TITLE
ready to published as an npm package and on bower registry

### PR DESCRIPTION
**Pull request by fibo**
I used [svg.draggable.js](https://github.com/wout/svg.draggable.js) as a template. The _manual-test.html_ was readapted and it is working.

I am not really sure about the author field and the ownership of the package: I forked it from [your fork](https://github.com/FlorianLoch/svg.foreignobject.js) of the [original one](https://github.com/memloom-development/svg.foreignobject.js).

Anyway, even if I actually created the package, there is no problem for me if you or someone else is registered as the owner: I just want to use this code for my project.

Please note that the repo https://github.com/wout/svg.foreignobject.js, referenced in package.json and bower.json should be created.

There is no hurry for my by now to publish it on npm, by the way, if you will not publish it in the next 6 month or so or until I will need this package for my project [flow-view](http://g14n.info/flow-view) I will do it and then I can give you a commit bit.

### CODE REVIEW

**Comment by FlorianLoch** [comment]
Hello Gianluca,
thank you for your request - I will have a closer look at it at the weekend.

Best regards
Florian 

## 

Florian Loch
florian.loch@gmail.com mailto:florian.loch@gmail.com
Mobil: +4917691354966
Tennesseeallee 28
76149 Karlsruhe

**Comment by fibo** [comment]
Hi Florian,
thank you for svg.js! It is the best choice I found for my [dataflow programmin project](http://g14n.info/dflow).

By now this is the minimum I can do, contributing back with software.
BR,
Gianluca.

**Comment by FlorianLoch** [comment]
So, I took a look at it and I would like to annotate some things:
I forked the repo from `memloom-development`and fix an issue. But he never merged my changes stored in branch `patch-1`. You forked from my repo to make it ready for `svg.js 2.0`but unfortunately you forked from the main branch not containing my changes to memloom's source. So you actually forked his code :)
I guess you should refork from my patch branch or work in these changes to your code. Then I will merge the request, hoping that memloom will merge mine afterwards. Then he can push the module to npm. If he doesn't we can do it on ourselves. ;)

`svg.js`isn't a project of mine - I just contributed to some plugins ;)

**Comment by fibo** [comment]
mmh, it is easier if you merge both my pull request and your patch-1 branch all together into the master, than publish it on npm directly.

**Comment by FlorianLoch** [comment]
Ok.
I merged it, enhanced test file and fixed some "errors" spotted by eslint

**Comment by fibo** [comment]
Yeah!
Please note that the homepage is https://github.com/wout/svg.foreignobject.js, i.e. the repo should be published by @wout.

btw today I released [flow-view](http://g14n.info/flow-view/) which uses this package and also sv.draggable.js, yeahhh!

**Comment by FlorianLoch** [comment]
Wout didn't answer till now - so I guess he won't do anymore...

Why does it has to be exactly that homepage?

**Comment by fibo** [comment]
Just because I copied it from svg.draggable.js and I guess Wout liked to keep this plugin under his control. It is ok if you want to change the homepage, put it under your account and push on npm, or I can do it if you want.

**Pull request merged**
